### ISSUE TITLE
[Feature Request] Toggle option

### ISSUE THREAD

**Issue by AStrangeMouse** [ZsoltMolnarrr/BetterCombat#122]
**"I read project readme, checked client side and server side configurations, and no such feature exists"** - Yes, unless I missed something.

**"Is your feature request related to a problem? Please describe."** - For general compatibility overall. It would eliminate semantic incompatibility.

**"Describe the solution you'd like"** - A toggle option (preferably with a keybind) to disable/enable Better Combat for yourself, allowing inherent compatibility with any mod that can overwrite the player model (such as Dragon Survival, etc) on a per-person basis. Essentially, if one uses a mod that overwrites the player model, they could toggle and revert to vanilla behavior for themselves, while others could still be using Better Combat at the same time.

**Comment by ZsoltMolnarrr** [comment]
Better Combat discord frequently asked channel:

**Can you add a Battle Mode toggle?**
First let's clarify, this mod is not Nicer Combat, so it is not just adding animations. There is a whole new attack system under those animations, that includes the upswing mechanic and accurate weapon collision detection.
Toggling on/off the new attack system would be really bad, since players would be able to choose between instant long range hit with swords and delayed short range attacks, granting an easy way to cheat/cheese any fighting scenario.
Battle mode like toggle will not be added.

**Comment by ZsoltMolnarrr** [comment]
The suggestion would result an unstable and inconsistent gameplay experience.
Nor would it solve the eliminate semantic incompatibility, it would just rather try to patch it.

**Comment by AStrangeMouse** [comment]
> The suggestion would result an unstable and inconsistent gameplay experience. Nor would it solve the eliminate semantic incompatibility, it would just rather try to patch it.

That could be solved by including a server config option to enable/disable players being able to toggle. Which then leaves the decision up to server owners. Especially if they are not attempting to establish a competitive setting, or are playing with people they trust.

And patching would specifically be the point, of course - because semantic incompatibilities are out of the question, so it would be nice to have _some_ alternative that works overall, in place of nothing.

Regarding the former comment: While I do understand there's an entire underlying framework to the combat, and that it's not simply just animations, would a quick internal hook be too complicated? There's got to be an underlying check of some kind that could be performed to disable when another mod determines that someone has become, say, a dragon or whatever else.
