### ISSUE TITLE
LevelZ mod

### ISSUE THREAD

**Issue by ZsoltMolnarrr** [ZsoltMolnarrr/BetterCombat#17]
[2022-07-21-7.log](https://github.com/ZsoltMolnarrr/BetterCombat/files/9163380/2022-07-21-7.log)

**Comment by chronosacaria** [comment]
Looks like there is a @Redirect in BetterCombat that is conflicting with a `@ModifyVariable` in LevelZ. Because of the `@Redirect`, the target that LevelZ is trying to get to isn't there anymore, so it crashes.

The code in question is as follows:
-- Better Combat --
[PlayerEntityInject#replaceSword](https://github.com/ZsoltMolnarrr/BetterCombat/blob/c083ea378745cda95e0cb1324848c2cfe3a06088/src/main/java/net/bettercombat/mixin/PlayerEntityInject.java#L34)
```java
@Redirect(method = "attack(Lnet/minecraft/entity/Entity;)V", at = @At(value = "INVOKE", target = "Lnet/minecraft/item/ItemStack;getItem()Lnet/minecraft/item/Item;"))
    public Item replaceSword(ItemStack instance) {
        if (WeaponRegistry.getAttributes(instance) != null) {
            return Items.AIR;
        } else {
            return instance.getItem();
        }
    }
```
-- LevelZ --
[PlayerEntityMixin#attackMixin](https://github.com/Globox1997/LevelZ/blob/78a854f161de969db7fd70e6efc87618551d3cdd/src/main/java/net/levelz/mixin/player/PlayerEntityMixin.java#L76)
```java
@ModifyVariable(method = "attack", at = @At(value = "INVOKE", target = "Lnet/minecraft/item/ItemStack;getItem()Lnet/minecraft/item/Item;"), ordinal = 2, require = 0)
    private boolean attackMixin(boolean original) {
        if (playerEntity.world.random.nextFloat() < (float) playerStatsManager.getLevel("luck") * ConfigInit.CONFIG.luckCritBonus) {
            isCrit = true;
            return true;
        } else
            isCrit = false;
        return original;
    }
```

**Comment by ZsoltMolnarrr** [comment]
I have been unable to resolve this issue so far.
I don't know how to make a non conflicting mixin for this case.
