### ISSUE TITLE
Error Code: 1 with 1.5.2 Battle combat of version 1.18.2

### ISSUE THREAD

**Issue by CoolySkater593** [ZsoltMolnarrr/BetterCombat#170]
**Minecraft version** - 1.18.2
**Mod loader** - Forge 40.1.86
**Mod version** - 1.5.2
**I am using the latest version available** - yes

**Describe the bug**
Getting Error Code: 1 once I click play

**To Reproduce**
1. Open Launcher
2. Click Play
3. Launcher Closes
4. Launcher Reopens with error code: 1

**Expected behavior**
The game would open up, no issues.

**Screenshots or video recordings**
![Error 1 Battle Combat Minecraft](https://user-images.githubusercontent.com/92769199/206971943-529a8852-aeb6-49a0-b56d-9ea8fb276854.png)

**Comment by ZsoltMolnarrr** [comment]
There can be multiple things causing this issue.
Here are some of them:
- pirated minecraft version
- faulty manual installation (missing or incorrect dependencies)
- Forge modloader version failing due to unknown reasons

Please use the CurseForge app, to install Better Combat, that will automatically resolve the correct dependencies for you.
Fabric version is recommended due to stability, performance and compatibility being superior.
