### ISSUE TITLE
Can`t join multiplayer

### ISSUE THREAD

**Issue by kino10** [ZsoltMolnarrr/BetterCombat#195]
**Minecraft version** - 1.19
**Mod loader** - TLauncher
**Mod version** - 1.5.4+1.19
**I am using the latest version available** - No

**Describe the bug**
With Better Combat mod Me and friend can`t join to each other. It kicks with internal connection error

**To Reproduce**
1. Go to 'Multiplayer'
2. Click on 'Join server'
3. See error

**Comment by ZsoltMolnarrr** [comment]
Does the server have the mod installed?

**Comment by kino10** [comment]
yeah, sure. We have a few mods just for optimization and only with this mod we can`t join

**Comment by ZsoltMolnarrr** [comment]
Make sure to use the latest version from all mods, and everyone to have the same set of mods.
No support is provided for old versions.

Also please provide actionable information (crash report or error logs), otherwise the issue will be closed.
If you cant provide information, I recommend joining the Better Combat discord where you can ask other people running servers.

**Comment by kino10** [comment]
Ok, I`ll check if all required mod are latest version. But can`t show info about crash rn. I`ll do it when I will able to
