### ISSUE TITLE
First person being weird

### ISSUE THREAD

**Issue by Vividcal** [ZsoltMolnarrr/BetterCombat#206]
Downloaded everything such as the mod menu, however when i slash with first person being enabled it zooms me out into third person and zooms me back in on first person

**Comment by ZsoltMolnarrr** [comment]
Better Combat does nothing like that, I recommend checking out what other mod is causing that.

**Comment by ZsoltMolnarrr** [comment]
Additional info that might help.

Better Combat discord FAQ:
**Whenever I swing a weapon in First person, my head shows up and it  blocks the screen fully. How to fix?**
This kind of problem is typically caused by another mod that handles renderstates in a faulty way.
Many of these (formerly incompatible) mods have been fixed in the recent months. Please try updating all of the installed mods.
Usual suspects: Twilight Forest (fixed with update), Minecraft Comes Alive Reborn (issue still open)
