### ISSUE TITLE
Make Attack Range Editable via items from other mods (e.g. arm extender in Things mod)

### ISSUE THREAD

**Issue by ereese99** [ZsoltMolnarrr/BetterCombat#227]
**I read project readme, checked client side and server side configurations, and no such feature exists** - YES

**Is your feature request related to a problem? Please describe.**
Any items (such as the arm extender in Things mod) that modify attack range do NOT work. I'm sure this is already known by devs, but I think it really should be implemented.

**Describe the solution you'd like**
When equipping trinkets that extend your attack range, they should WORK

**Describe alternatives you've considered**
No alternatives other than what currently happens: nothing...

**Comment by ZsoltMolnarrr** [comment]
Better Combat FAQ:

**Why are my attack range increasing buff/enchantments/gems not working?**
Better Combat defines its own attack range attribute. This attack range is designed to be a non changeable, intrinsic property of weapons.
Increasing range of melee attacks with buffs/enchants/gems has the following problems:
- It is an absolutely unbalanceable mechanic (both PVP and PVE)
- Allows non sense scenarios like: a fist weapon that has bigger range than a glaive
- Detaches attack animations from attack hitboxes to such an unrealistic extent, it hurts user experience
- Overloads attack collision detection
No wonder, that no properly designed game (I know of) does increase attack range in such way. In every case this is an intrinsic property of the weapon or attack style. Just because something is possible to code, doesn't mean it should be.
To experience weapons with significantly different range, install some weapon mods adding a wider variety of weapons. Check out #🤝partnership
