### ISSUE TITLE
Broken animations in third person

### ISSUE THREAD

**Issue by evelynn999000** [ZsoltMolnarrr/BetterCombat#242]
**Minecraft version** - 1.19.2
**Mod loader** - fabric
**Mod version** - 1.6.2
**I am using the latest version available** - Yes

**Describe the bug**
When I go into third person I happen to have broken animations the weapons move the way they are supposed to in terms of direction but the actual swing animation like they are in first person are gone they just look like I'm punching with them if it's a spear, or smacking someone if it's a side to side motion not actually swinging say a scythe to reap someone, or thrusting a spear point into someone. (might be best to say the weapons don't point correctly?) thing is it works for everyone else around me they even see my messed up animations but can't find a fix.

**To Reproduce**
1. Go in third person
2. Attack

**Expected behavior**
When you attack weapons don't move properly

**Screenshots or video recordings**
If someone can get in discord with me I can show them but I don't know how to do recording stuff and I'm too slow to get a screenshot.

**Additional context**
none ask anything I might be able top provide more.

**Comment by evelynn999000** [comment]
(I did do a quick test on my forge server and it works perfectly fine on forge.) I've also tested it in singleplayer.

**Comment by ZsoltMolnarrr** [comment]
Hello!
I mainly use Fabric and have never observed any such issue.
I need actionable information, video footage to be specfic.
Also I need your help to find out which other mod is causing this.

**Comment by LukeNight9880** [comment]
If you have a video software I can try to do it (it's the same person just different account can't find my long in info) Just idk any nor how to use it. Hence why I said I could show it on discord.

Edit: I found one on overwolf and uploaded it to YT sending it soon gonna take about an hour to upload. Since it only likes 10mb's here.

**Comment by LukeNight9880** [comment]
Or not and it chose to upload fast :/ https://www.youtube.com/watch?v=i4AWiLzSMoM&ab_channel=Nucleon%27sSoul

here's the modpack we are using so it has all the mods https://www.curseforge.com/minecraft/modpacks/wolfqueens-origins

but don't understand what caused it. It's on all fabric now and it was working fine a few days ago. Everyone else see's the bug but they don't have it.

**Comment by ZsoltMolnarrr** [comment]
This issue is caused by the mod that transform your player model into naga.
Mods those change or replace the player model are explicitly stated as incompatible. https://github.com/ZsoltMolnarrr/BetterCombat#-mod-compatibility

There is absolutely nothing I can do to fix this.
If you would like to get this fixed, I recommend reaching out to the developer of the mod in question, in order to implement proper compatibility with the PlayerAnimator library.

**Comment by LukeNight9880** [comment]
May want to add that to the front page of the mod page as well cause it never stated this.
![Screenshot 2023-04-22 123515](https://user-images.githubusercontent.com/121647374/233796184-63bb0fba-eed2-44b8-a2b5-df6676291189.png)
Thx though.
