### ISSUE TITLE
Changes to default sweeping and to duel wielding speed

### ISSUE THREAD

**Issue by BluBangs** [ZsoltMolnarrr/BetterCombat#245]
**I read project readme, checked client side and server side configurations, and no such feature exists** - No

**Is your feature request related to a problem? Please describe.**
Everyone in the server I'm in has been having gripes with the default sweeping edge that's on every weapon _also_ attacking their pets, villagers, other farm animals than the one they actually wanted to kill, and other mobs they just don't want to hurt.

**Describe the solution you'd like**
Simple, but effective, is a keybind to turn either the sweeping edge off, or the entire mod off, bringing the combat style back to vanilla. That would also solve the solution of people who don't want to fight with better combat being able to fight in the vanilla style without completely removing the mod, which would absolutely ruin everyone else's experience.

**Is your feature request related to a problem? Please describe.**
There's another problem other people have with the mod which is that the duel wielding adds too much speed to weapons a different mod adds, making those weapons severely overpowered. The mod has several weapons with great speed in return for less damage, and the other players dislike that the duel wielding makes those weapons fast enough to destroy several mobs within a second even with the lowered damage.

**Describe the solution you'd like**
One solution would be to give weapons a gradual decline in the speed multiplier duel wielding gives them, such as two swords having a larger multiplier compared to two weapons with 3 base attack speed, and two weapons with 4 attack speed having a smaller multiplier than the weapons with 3 base attack speed, gradually getting smaller so that already good weapons don't become game breakingly fast.

**Describe alternatives you've considered**
Another solution, or even a solution that could be added alongside the other solution, for the speed would be a hard cap so that weapons can only go so fast. Obviously this speed can be changed in the configs for the individual servers, and that can still be a solution if this doesn't get implemented, however having it in the mod itself would make less servers need to change the speed.

Also, sorry for the mass of text, I don't suggest changes to mods or use github very often, so I don't know what level of professionalism or detail I actually need to use here.

**Comment by ZsoltMolnarrr** [comment]
There is no way to disable sweeping edge, because there is no sweeping edge in Better Combat. What you call sweeping edge is the geometrically approximated weapon swing trajectory (or in other words: weapon collision detection). Disabling this would put back vanilla raycasting, which is essentially pixel hunting for target infront. I believe the removal of such major feature would not make any sense, so I believe this problem should have a different solution.

This problem described was solved months ago, when proper friend or foe logic was added to protect pets and villagers.

What version of the mod are you using?
What exactly is the server configuration?

Reflecting on weapon speed issue.
Better Combat does not change the attack cooldown (aka attack speed) of any weapons.
It is true that dual wielding gives a weapon speed boost. But damage output and attack speed boost **while dual wielding** can both be adjusted in server config.

**Comment by BluBangs** [comment]
We're using 1.6.2+1.19, playing in 1.19.2 with default settings, I don't know if that .2 would make a difference, but then I'm not the one who set up the server and this isn't my area of expertise. I'm here on behalf of someone else who got mad about the mod for this exact reason. If the difference between .0 and .2 makes as big of a difference as breaking the pet protection, I'll let them know and keep bugging them about it until they change to the correct mod. Also, thank you for responding to something apparently very obvious.

**Comment by ZsoltMolnarrr** [comment]
Please provide the server configuration of Better Combat to continue the investigation.
