### ISSUE TITLE
Incompatibility with The Aether or Forge's Reach Boost

### ISSUE THREAD

**Issue by nocturni** [ZsoltMolnarrr/BetterCombat#266]
**Minecraft version** - ?
1.19.4

**Mod loader** - ?
Forge

**Mod version** - ?
1.7.1

**I am using the latest version available** - ?
Yes (for 1.19.4)

**Describe the bug**
Valkyrie Lance doesn't hit from far distances, its reach boost doesn't seem to apply when attacking.

**To Reproduce**
1. Download and install The Aether from Modrinth/Curseforge
2. Take the Valkyrie Lance
3. Can break blocks from a certain distance, but not deal damage

**Expected behavior**

**Screenshots or video recordings**
I can't really add screenshots, it just doesn't hit from far.

**Additional context**
I've been told from an Aether developer that this is a conflict with Better Combat and Forge, that provides the ability to add Reach Boost to weapons

**Comment by Shadows-of-Fire** [comment]
The author of this mod has no intention to be compatible with forge's API, see: https://github.com/ZsoltMolnarrr/BetterCombat/issues/244

I'm considering marking Apotheosis as incompatible with BC due to the number of complaints I receive about it, I might suggest Aether do the same.

**Comment by ZsoltMolnarrr** [comment]
Just because something is possible to be turned into an attribute, doesn't make it a valid/good idea.
Can you name a single logically valid usecase, where attack reach can be increased by attribute buffs and is represented correctly in visuals? If so how should I implement it?
Can you name a single other game where this concept happens to be implemented correctly and is intuitive for players?

**Comment by ZsoltMolnarrr** [comment]
Closing, the issue based on declared compatibility (readme bottom) list.
But I will keep replying to related message here.

**Comment by Mecheon** [comment]
- Can you name a single logically valid usecase, where attack reach can be increased by attribute buffs and is represented correctly in visuals? If so how should I implement it?

While I don't think anyone's created a mod, its entirelly plausible some sort of magic mod could do a 'pre-buff yourself so your next swing is at a wider range' spell or similar. "Aura blades" and the like are a common enough concept in fiction and the visual discrepency could be handled by whatever effect said mod does when the swing happens

- Can you name a single other game where this concept happens to be implemented correctly and is intuitive for players?

Terraria. Also if going specifically a 'charge and sword goes longer', Kirby, Super Smash Bro's smash attacks, and the sword spin from various Legend of Zeldas, though Ocarina of Time provides the best example of the 'charge for a longer distance around you'

**Comment by nocturni** [comment]
I think that it shouldn't be Better Combat's problem if it's intuitive or not, while it might look weird to some, it also looks "weird" in vanilla, it's a reach boost after all so yeah, that's not really seen in the base game. A toggleable option would be cool, at least modpack makers could choose if they want it or not, I don't see why it's worth breaking compatibility with lots of mods just because it "looks weird", right now it's just breaking the progression of many mods, including the Aether's. The mod presents itself as highly configurable.. why should this be excluded?

**Comment by ZsoltMolnarrr** [comment]
Non-logical / non-intuitive features are not implemented, because most of the audience doesn't need them, and I can spend my time developing actually useful/fun things.

I disagree with all of the reasons why this should be implemented. The ability to make a fist weapon longer reach than (in any possible way) than a spear, is just downright broken, not a source of entertainment.
There is a clear reason why Minecraft Dungeons does not have a mechanic like this.

However, in order satisfy expectation and spend less time arguing, I am going to add an API to extend the range technically. So third party developers will be able to inject range modifiers into targeting logic of Better Combat, via a dedicated Java API. This will be kept up to date alongside with the mod source, however if performance issues arise (such as collision detection algorythm overloaded by huge range) those will be just ignored based on disclaimers in the past.
Note no attack animation or visualisation will be changed by this.

**Comment by Shadows-of-Fire** [comment]
That response is disappointing. Just use the API forge already has for this exact purpose instead of circumventing it.

This is a sandbox game, the stance you're taking is like saying nothing should ever increase Step Height because it gets weird above a certain point.

**Comment by ZsoltMolnarrr** [comment]
Just stepping over reasonable argument points is also disappointing. (Especially about the ability to create nonsense game scenarios). Yes this is a sandbox game, but is it really that important to be able to create nonsense or glitchy looking game scenarios, instead of working on more mainstream content?

Also note, this mod is not for Forge only.

Please let me where the documentation of that attribute resides, and also how exactly should I integrate/calculate with it? (Given that Better Combat weapon attributes have an absolute attack range value)
