### ISSUE TITLE
Language support is broken

### ISSUE THREAD

**Issue by ildiem** [ZsoltMolnarrr/BetterCombat#274]
**Minecraft version** - 1.19.2
**Mod loader** - Forge 43.2.21
**Mod version** - 1.7.1+1.19
**I am using the latest version available** - yes

**Describe the bug**
Better Combat doesn't seem to recognize any lang files besides its default en_us values. I came across this while making a resource pack trying to modify en_us, but I also tried changing the language in-game to something the mod should support and the mod was still in en_us.

**To Reproduce**
1. Create and run fresh installation with Better Combat
2. Select any supported language (I chose es_es)
3. All text added by Better Combat is still in en_us

**Expected behavior**
Lang files should be respected

**Comment by ZsoltMolnarrr** [comment]
Non actionable issue due to the following:
- es_es language file is maintained by volunteers, it maybe a partial translation only. Whoever wants to see this improved needs to send improved language file as PR
- Better Combat has **zero** code related to languages. If your selected language file doesn't load it is likely an issue of Minecraft itself, but even more likely Forge.
(Forge modloader is wastly unstable)
