### ISSUE TITLE
Jump attacks

### ISSUE THREAD

**Issue by gitguette** [ZsoltMolnarrr/BetterCombat#285]
**I read project readme, checked client side and server side configurations, and no such feature exists** - YES/NO
Yes

**Is your feature request related to a problem? Please describe.**
I always feel like attacking while jumping is weird. The timing feels strange and unnatural, especially with slower weapons. The animation also looks out of place.

**Describe the solution you'd like**
A custom attack if the player is in the air that strikes the ground and perhaps causes an aoe affect, similar to breath of the wild.

**Describe alternatives you've considered**
Random crits instead of jump are another way to make it better, but I would still like to attack from midair for more variety in combat.

**Comment by ZsoltMolnarrr** [comment]
This will definitely not be implemented.
This suggestion would:
- Require introducing new crit related attributes and enchantments  (there are already mods out there to do this)
- Break existing modpacks relying on the vanilla crit feature (since new attributes cannot be introduced conditionally)
- Conflict with other mods achieving what you are looking for.

I put great emphasis on making attacks feel more real than vanilla, I think they are good. If you don't like it, I am sorry, too bad.

Jumping attacks might be weird if you expect instantaneous attacks with absolutely zero realism. When using this mod, you have to time the attacks by taking into account the windup time of the weapons (which is by the way configureable).
