### ISSUE TITLE
Mod causing the game as a whole to break and not make axes work as intended.

### ISSUE THREAD

**Issue by ChibiRuby** [ZsoltMolnarrr/BetterCombat#310]
Minecraft version - 1.18.2
Mod loader - Forge 40.2.14
Mod version - 1.6.2
I am using the latest version available - Yes

Describe the bug
World and mod works fine and as intended for a while. All of a sudden, axes are not able to accelerate mining of wood no matter if the axe is vanilla or modded, high tier or low tier and so on. This has happened multiple times and the only way to fix this issue is creating a new instance and manually downloading the same mods from scratch one by one. You cannot switch the same mods to another instance, the problem repeats itself even if it has never had the same mod before. Deleting the mod doesn't fix it. This issue has only started occurring once I started to use BC. I've tried using the fix in Issue number #233 to no avail.

List of Mods used.
![image_2023-12-11_180343661](https://github.com/ZsoltMolnarrr/BetterCombat/assets/130272909/f785aab4-e907-40cb-a975-468da35f9383) 

To Reproduce
Completely Random, I don't have a single clue how this issue arises.

Expected behavior
Axes to mine wood properly.

**Comment by ChibiRuby** [comment]
To add to this, what's wilder is that the config file is showing an exception for Farmer's Delight stuff but I've only installed the mod once a month back.

**Comment by ZsoltMolnarrr** [comment]
1.18.2 versions are no longer being developed, you can use them as they are or update to a newer game version.

That being said your issue is most likely just some bad clientside configuration. Make sure to use the GUI config, and dont tinker with JSON5 files.

In case the issue resurfaces on a newer game version, please provide the absolute minimum set of mods (not more than 4) to reproduce this issue, and also some video footage to show the exact problem.

**Comment by tsokiyZan** [comment]
This still occurs in 1.20.1 versions of the mod, and the fix you posted for #233 did not work. Also you said directly in #233 to tinker with JSON5 files, you gave the path to one and said what to replace in it. Furthermore there is no option in the GUI to change fallback_compatability.json
