### ISSUE TITLE
Attack through walls

### ISSUE THREAD

**Issue by Fleyzi** [ZsoltMolnarrr/BetterCombat#32]
If you turn off "Mine with weapons" you can hit mobs through any walls or obstacles. It also works with turned on "Mine with weapons" if you start attack any entity then turn arround and hit mob through walls.

Fabric Loader: 0.14.8
Fabric API: 0.58.0+1.18.2
Mod version: 1.0.5

Preview:
https://user-images.githubusercontent.com/36078397/182436008-cbed4589-1929-416c-9d88-f6a6cc1df8c7.mp4

**Comment by ZsoltMolnarrr** [comment]
This is expected behaviour.
It works the same in Minecraft Dungeons.

We might implement something against this in the future, however this is not trivial task.
Theoretically we could perform a raytrace, using the distance vector we get from collision detection. However this might have to be performed against hundreds of targets, which would maybe result in a huge lagspike.
