### ISSUE TITLE
Negative Attack Speed

### ISSUE THREAD

**Issue by SaikoTSP** [ZsoltMolnarrr/BetterCombat#328]
Minecraft 1.20.1
Forge
1.8.1
I am using the latest version available

**Describe the bug**
Whenever a sword has negative swing speed, it basically becomes unswingable, theres certain mods that adds swords with negative swing speed, therefore the swords are unusable.

**To Reproduce**
1. Launch Vanilla Minecraft (or disable BetterCombat)
2. Set a negative generic attack speed, swing your sword, it works
3. Enable BetterCombat, set a negative generic attack speed, swing your sword
4. It won't swing

**Expected behavior**
I think it should behave like Vanilla Minecraft, since it still swings.

**Comment by ZsoltMolnarrr** [comment]
Attack speed is meant to be handled within reasonable range.
What is the attribute value of attack speed in your case?

**Comment by SaikoTSP** [comment]
-4.1 since the sword adds negative 4.1 to the base 4 attack speed of the player. There's a second sword that adds negative 4, turning the attack speed to 0

**Comment by ZsoltMolnarrr** [comment]
What is the expected rate (attacks per second) at speed 0?

**Comment by SaikoTSP** [comment]
Idk, so the swords are basically unusable with better combat, that's it?

**Comment by ZsoltMolnarrr** [comment]
Umm I don't think so.
I am still trying to understand what a negative attack speed would look like.

**Comment by Shibva** [comment]
@ZsoltMolnarrr this issue is a bit valid actually

Mana and Artifice have this issue that renders functionality construct parts invalid 

![Image](https://github.com/user-attachments/assets/357b0639-298a-41d8-a4a5-028926016149)

This prevents the item from being used as a weapon and interacting.

putting it on the fallback blacklist still prevents the item from being used as a weapon but it no longer prevents it from being used to right click on things.
