### ISSUE TITLE
Support for 1.20.4

### ISSUE THREAD

**Issue by EchoEllet** [ZsoltMolnarrr/BetterCombat#331]
Port this mod to 1.20.4 since that version fixes a few connection issues.

**Comment by aurorarissime** [comment]
Any update on this being officially implemented?

**Comment by ellet0** [comment]
> Any update on this being officially implemented?

No, this is not official. I did it because the members of the server really needed the mod

We tested it, and it worked like expected, no unexpected behavior or crashes, even though I think it has one small bug for the horse

See the comments for more info

**Comment by ZsoltMolnarrr** [comment]
I will work on it, as soon as I have time for this.

Please keep in mind, all of these projects are developed and maintained on spare time.

**Comment by ZsoltMolnarrr** [comment]
The project will be updated eventually. This issue has no purpose.

**Comment by ellet0** [comment]
> This issue has no purpose.

It depends on how you see it

**Comment by ellet0** [comment]
> I will work on it, as soon as I have time for this.
> 
> Please keep in mind, all of these projects are developed and maintained on spare time.


Thank you for your time and efforts to this project, I already updated it for 1.20.4 as the time of this issue in this [PR](https://github.com/ZsoltMolnarrr/BetterCombat/pull/332), I know this is just a hobby project and not your main work which is why I said "I'm ready to pay the authors", most open source projects live on donations and contributions
