### ISSUE TITLE
Apparent Better Combat and YDM Weapon's Master Dual Wield incompatiblity

### ISSUE THREAD

**Issue by Yuubarashi** [ZsoltMolnarrr/BetterCombat#418]
**Minecraft version** - 1.20.1
**Mod loader** - Fabric
**Mod version** - 1.8.6
**I am using the latest version available** - Yes

**Describe the bug**
When using both mods the off hand weapon doesn't render, but the hand does the animation.

**To Reproduce**
1. Install both YDM Weapon's Master and Better Combat.
2. Enter a world
3. Wield dual weapons
4. The off-hand weapon doesn't render.

**Expected behavior**
The off-hand weapon renders normally.

**Screenshots or video recordings**

https://github.com/user-attachments/assets/0db33304-9d44-4685-94f8-be8778d55de4

(When attacking hostile mobs behaves the same)

**Additional context**
Im making an inmervise vanilla Modpack, so I'm using both mods to achieve that.

Whoever there's a rudementary solution, if you disable the off-hand render in YDM Weapon's Master it will work how intended.

But what I want to achieve is: when not fighting or using the off-hand the tool goes to your leg, which is not possible with the former solution, is either having the off-hand tool in your hand all the time or not being able to see the dual wielding properly.

(Sorry if there's any typo, I use spanish as my first language)

**Comment by ZsoltMolnarrr** [comment]
Please read project goals: https://github.com/ZsoltMolnarrr/BetterCombat
Specifically the part, that Better Combat is a low level mod, adding no support for content mods from Better Combats direction towards content mods. It would make Better Combat unsustainable to maintain, and make compatibility with other content mods hardly possible.

Hence, content mods need to ensure their own compatibility with Better Combat, in case they desire so.

Moreover, some mods may need to disable some of their own features, to be compatible with Better Combat, due to some features potentially overlapping, which is happening in this specific scenario.

A disclaimer about this is clearly stated here: https://github.com/ZsoltMolnarrr/BetterCombat#-mod-compatibility


Closing due to being non-actionable from the perspective of this repository.
