### ISSUE TITLE
[Forge 1.18.2] First-person animations invisible when using with Wizard Staff mod

### ISSUE THREAD

**Issue by tharrmeehan** [ZsoltMolnarrr/BetterCombat#61]
**Minecraft version** - 1.18.2
**Mod loader** - Forge
**Mod version** - 1.1.0
**I am using the latest version available** - Yes

**Describe the bug**
When using this mod with the Wizard Staff mod (https://www.curseforge.com/minecraft/mc-mods/wizard-staff) , all the animations turn invisible in first person mode, this does not happen in third person. This is an incompatibility from Wizard Staff due to their use of custom animations.

**To Reproduce**
1. Download all the mods
2. Create/Join a world
3. When attacking something, you won't see anything. No animation or weapon, only sounds.

**Expected behavior**
Animations should world as expected.

**Screenshots or video recordings**
![image](https://user-images.githubusercontent.com/58373200/186476928-dc402b7e-63aa-41e3-a159-a38cf16f74af.png)

**Comment by ZsoltMolnarrr** [comment]
Hello!
Thank you for specifying the exact problem, this is a valid issue.

**Comment by ZsoltMolnarrr** [comment]
Wizard Staff touches lots of render related code.
Our solutions seem to conflict in a way that I don't understand.
I don't see a way to fix it on this end, since Better Combat is already using the miminal possible mixins for first person attack animation implementation.

Please create an issue at Wizard Staff repo.

**Comment by tharrmeehan** [comment]
Thank you, I will try to get in contact with them.
