### ISSUE TITLE
[Forge] Better Third Person Compat / Make combat animations depend on what direction the model is facing instead of crosshair

### ISSUE THREAD

**Issue by Keldera** [ZsoltMolnarrr/BetterCombat#82]
**I read project readme, checked client side and server side configurations, and no such feature exists** - YES

[edit] 
Mod Versions
Forge - 1.18.2 - 40.1.73
bettercombat-forge-1.1.1+1.18.2
BetterThirdPerson-Forge-1.18.2-1.8.1
[end edit]

**Is your feature request related to a problem? Please describe.**
Trying to use Better Third Person and Better Combat together, I discovered that the directional attacking in B3P does not apply to BC's attacks due to the player model and attack animation snapping to the camera's vector.

**Describe the solution you'd like**
I would like for Better Combat to affect the directional attacking from Better Third Person instead of overriding it with vanilla 3rd person behavior.

**Describe alternatives you've considered**
If BC's combat animations were to stay with a player's model facing direction instead of locking to camera direction, I believe B3P's directional attacking would function as it normally does.

**Additional context**
Epic Fight Mod also has this incompatibility with Better Third Person, or at least it did some time ago, I am not sure if it has been addressed there.

**Comment by ZsoltMolnarrr** [comment]
Better Third Person has an option named `Aim Player on Interact` which is you need to set to `NO` in order to work as you expect it.
On the Fabric version of the B3P you can access the settings of B3P, to change this setting.
On the Forge version I cannot seem to find a way to change this setting.
So the issue has to be solved on B3P side.

Feel free to reference this comment when making an issue for B3P.
I suggest them to use Cloth-Config, so the functional parity (between Fabric and Forge) of client side settings is easy to solve.
https://github.com/ZsoltMolnarrr/BetterCombat/blob/947767cda06cd1b1c91e9d176d1e581023fe2bb1/forge/src/main/java/net/bettercombat/forge/BetterCombatForge.java#L28
