### ISSUE TITLE
[Fabric] The Requiem mod

### ISSUE THREAD

**Issue by cymophic** [ZsoltMolnarrr/BetterCombat#83]
**Minecraft version** - 1.19
**Mod loader** - Fabric
**Mod version** - 1.19-1.19.2 version
**I am using the latest version available** - Yes 

**Describe the bug**
Crash on startup after adding it to personal modpack that otherwise runs smoothly

**To Reproduce**
1. Open Minecraft

**Expected behavior**
Run Minecraft

**Crash Log**

[crash-2022-08-28_19.06.03-client.txt](https://github.com/ZsoltMolnarrr/BetterCombat/files/9439524/crash-2022-08-28_19.06.03-client.txt)

**Comment by ZsoltMolnarrr** [comment]
Hello!
This is an incompatibility with some other mod.
I couldn't find which mod causes it.

It would be very helpful, if you could investigate which mod causes exactly this. This can be done by enabling/disabling mods individually.

**Comment by thedeerirty** [comment]
I'm having a similar issue, or rather, the exact same one that's describe in the crash report here, on Fabric 1.18.2.

I can remove the mod it names in the first line, but launching after the fact would then site another mod, causing a crash.

So far, the mods have been:

Biome Makeover, Carrier, and Adventure Z. The thing is, I'm not sure what about any of those mods that would logically generate an incompatibility, save Carrier. None of them really affect player animation

**Comment by thedeerirty** [comment]
Ah, incompatiblity located, at least for me.

The Reqieum mod seems to cause the crash, found so by looking at the .log

Not sure if it is the same for this guy though, and I may also have an out of date Reqieum version. I will check on that one.

edit: I do have up to date reqieum.

**Comment by thedeerirty** [comment]
Yep, alright; Did some testing and heres what I can come up with for certain:

100%, for my version of error, is Reqieum. I didn't look through this dude's modlist, but my guess would be he has a mod that signifigantly changes his player model in someway. Not sure if the same can be said for forge, but if anyone else throws a similar error check their latest.log; for me that revealed it was reqieum 

What Reqieum does, in case you may not be aware, basically makes the player like a ghostly goo; instead of dying, you get forced out of your body and can possess other mods. It's a whole thing, very fun. However, I imagine that's the part that is conflicting with your end of things.

My question is, how much of a possiblity is there for any form of combatibility on this? I'm not really interested in using the fighting mechanics as a mob per say, but I'd like to run them both without crashing if you feel me.

**Comment by ZsoltMolnarrr** [comment]
Both mods are targeting the same `LivingEntityRenderer.features` field.

I see no way to resolve it on my end.

Better Combat:
https://github.com/ZsoltMolnarrr/BetterCombat/blob/1.19.X/common/src/main/java/net/bettercombat/mixin/client/firstpersonrender/LivingEntityRendererMixin.java

The Requiem:
https://github.com/Ladysnake/Requiem/blob/1.19/src/main/java/ladysnake/requiem/mixin/client/remnant/LivingEntityRendererMixin.java

I am open for technical suggestions.

**Comment by thedeerirty** [comment]
Hm, I see I see

I'll get an opinion from my pal who does some coding, see if he has any sort of vague idea, but his experience is solely forge and my lack of knowledge on their specific differences doesn't know how much the knowledge will correlate

**Comment by thedeerirty** [comment]
Yo, I'm not sure what you (or the Reqieum) did, but on 1.19 I just noticed I was able to actual boot the mods together. Didn't check interaction besides that (I had forgotten I even downloaded Reqiem) but worth noting I feel.

**Comment by Sunconure11** [comment]
https://github.com/Ladysnake/Requiem/issues/580

It's still present, and it appeared in the Rats Mischief mod because of how it uses a stripped down build of Requiem for usage in a feature.

@ZsoltMolnarrr @Pyrofab @doctor4t @UpcraftLP @arathain

**Comment by ZsoltMolnarrr** [comment]
Can you help to specify which mixin exactly is causing the problem?

**Comment by Sunconure11** [comment]
Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Redirector doesPossessorHaveVehicle(Lnet/minecraft/class_1309;)Z in mixins.requiem.client.json:possession.LivingEntityRendererMixin from mod requiem failed injection check, (0/1) succeeded. Scanned 1 target(s). Using refmap requiem-refmap.json

**Comment by Sunconure11** [comment]
https://pastebin.com/iLeCaNK3

**Comment by Sunconure11** [comment]
`	Caused by: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: Implicit variable modifier injection failed in net/minecraft/client/render/entity/LivingEntityRenderer::emptyFeatures [INJECT Applicator Phase -> #requiem-lite:mixins.requiem.client.json:remnant.LivingEntityRendererMixin from mod requiem-lite -> Apply Injections ->  -> Inject -> #requiem-lite:mixins.requiem.client.json:remnant.LivingEntityRendererMixin from mod requiem-lite->@ModifyVariable::emptyFeatures(Ljava/util/Iterator;Lnet/minecraft/entity/LivingEntity;FFLnet/minecraft/client/util/math/MatrixStack;Lnet/minecraft/client/render/VertexConsumerProvider;I)Ljava/util/Iterator;]`
